name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Change this if you want a different branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=saadiqayyum/mongosh
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Update Kubernetes Deployment
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          IMAGE_NAME=saadiqayyum/mongosh
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          kubectl set image deployment/app-name app-container=$IMAGE_NAME:$TAG --namespace=default
